-- SHELF_NAME
ALTER TABLE "SHELFS"
ADD CONSTRAINT "CK_SHELFS_SHELF_NAME"
CHECK (
  REGEXP_LIKE(SHELF_NAME, '^[A-Z]*$')
);

-- SHELF_NUMBER
ALTER TABLE "SHELFS"
ADD CONSTRAINT "CK_SHELFS_SHELF_NUMBER"
CHECK (
  SHELF_NUMBER >= 0
);