-- METAL_PRICE
ALTER TABLE "METALS"
ADD CONSTRAINT "CK_METALS_METAL_PRICE"
CHECK (
  METAL_PRICE >= 0
);

ALTER TABLE "METALS"
ADD CONSTRAINT "CK_METALS_METAL_PROPERTY"
CHECK (
  METAL_PROPERTY IN (NULL, '1.4301', '1.4452', '1.6585', 'S235', 'S355')
);


ALTER TABLE "METALS"
ADD CONSTRAINT "CK_METALS_METAL_PROPERTY"
CHECK (
  METAL_TYPE IN (NULL, 'Geschliffen', 'Träne')
);