-- CITIES
ALTER TABLE "CITIES"
ADD CONSTRAINT "CK_CITY_CITIES_ID"
CHECK (
  REGEXP_LIKE(CITY_ID, '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
);

-- CONTACTS
ALTER TABLE "CONTACTS"
ADD CONSTRAINT "CK_CONTACTS_CONTACT_ID"
CHECK (
  REGEXP_LIKE(CONTACT_ID, '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
);

-- COUNTRIES
ALTER TABLE "COUNTRIES"
ADD CONSTRAINT "CK_COUNTRIES_COUNTRY_ID"
CHECK (
  REGEXP_LIKE(COUNTRY_ID, '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
);

-- EMPLOYEES
ALTER TABLE "EMPLOYEES"
ADD CONSTRAINT "CK_EMPLOYEES_EMPLOYEE_ID"
CHECK (
  REGEXP_LIKE(EMPLOYEE_ID, '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
);

-- METALS
ALTER TABLE "METALS"
ADD CONSTRAINT "CK_METALS_METAL_ID"
CHECK (
  REGEXP_LIKE(METAL_ID, '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
);

-- SHELFS
ALTER TABLE "SHELFS"
ADD CONSTRAINT "CK_SHELFS_SHELF_ID"
CHECK (
  REGEXP_LIKE(SHELF_ID, '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
);

-- STORAGE
ALTER TABLE "STORAGE"
ADD CONSTRAINT "CK_STORAGE_STORAGE_ID"
CHECK (
  REGEXP_LIKE(STORAGE_ID, '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
);