kind: pipeline
type: docker
name: latex

steps:

# BUILD
#######################################################################
- name: build-latest
  image: volkerraschek/container-latex:latest-archlinux
  commands:
  - make latexmk/index.pdf

- name: build-tagged
  image: volkerraschek/container-latex:latest-archlinux
  commands:
  - make latexmk/index.pdf
  environment:
    VERSION: ${DRONE_TAG}
  when:
    repo:
    - fh-trier/tgdb_ws1819
    event:
    - tag

# PUSH NEXTCLOUD
#######################################################################

- name: push-latest-nextcloud
  image: volkerraschek/container-latex:latest-archlinux
  commands:
  - curl --fail --user $WEBDAV_USER:$WEBDAV_PASSWORD --upload-file index.pdf --location $CLOUD_URL/remote.php/dav/files/$WEBDAV_USER/Dokumente/Studium/Fachschaftdaten/DB_1_-_Grundlagen_Datenbanken/Tutorien/Tutorium_WS1819/Tutorium_WS1819.pdf
  - curl --fail --user $WEBDAV_USER:$WEBDAV_PASSWORD --upload-file sql/schema_01.sql --location $CLOUD_URL/remote.php/dav/files/$WEBDAV_USER/Dokumente/Studium/Fachschaftdaten/DB_1_-_Grundlagen_Datenbanken/Tutorien/Tutorium_WS1819/schema.sql
  - curl --fail --user $WEBDAV_USER:$WEBDAV_PASSWORD --upload-file sql/sqlplus-settings.sql --location $CLOUD_URL/remote.php/dav/files/$WEBDAV_USER/Dokumente/Studium/Fachschaftdaten/DB_1_-_Grundlagen_Datenbanken/Tutorien/Tutorium_WS1819/sqlplus-settings.sql
  environment:
    CLOUD_URL:
      from_secret: cloud_url
    WEBDAV_USER:
      from_secret: webdav_username
    WEBDAV_PASSWORD:
      from_secret: webdav_password
  when:
    repo:
    - fh-trier/tgdb_ws1819
    event:
    - push
    - cron

- name: push-tagged-nextcloud
  image: volkerraschek/container-latex:latest-archlinux
  commands:
  - curl --fail --user $WEBDAV_USER:$WEBDAV_PASSWORD --upload-file index.pdf --location $CLOUD_URL/remote.php/dav/files/$WEBDAV_USER/Dokumente/Studium/Fachschaftdaten/DB_1_-_Grundlagen_Datenbanken/Tutorien/Tutorium_WS1819/Tutorium_WS1819_${DRONE_TAG}.pdf
  - curl --fail --user $WEBDAV_USER:$WEBDAV_PASSWORD --upload-file sql/schema_01.sql --location $CLOUD_URL/remote.php/dav/files/$WEBDAV_USER/Dokumente/Studium/Fachschaftdaten/DB_1_-_Grundlagen_Datenbanken/Tutorien/Tutorium_WS1819/schema_${DRONE_TAG}.sql
  - curl --fail --user $WEBDAV_USER:$WEBDAV_PASSWORD --upload-file sql/sqlplus-settings.sql --location $CLOUD_URL/remote.php/dav/files/$WEBDAV_USER/Dokumente/Studium/Fachschaftdaten/DB_1_-_Grundlagen_Datenbanken/Tutorien/Tutorium_WS1819/sqlplus-settings_${DRONE_TAG}.sql
  environment:
    CLOUD_URL:
      from_secret: cloud_url
    WEBDAV_USER:
      from_secret: webdav_username
    WEBDAV_PASSWORD:
      from_secret: webdav_password
  when:
    repo:
    - fh-trier/tgdb_ws1819
    event:
    - tag

# PUSH GITEA
#######################################################################

- name: push-tagged-gitea
  image: plugins/gitea-release
  settings:
    base_url: https://git.cryptic.systems
    api_key:
      from_secret: gitea_token
    files:
    - index.pdf
    - sql/schema_01.sql
    - sql/sqlplus-settings.sql
    checksum:
    - md5
    - sha1
    - sha256
    - sha512
    - adler32
    - crc32
  when:
    repo:
    - fh-trier/tgdb_ws1819
    event:
    - tag

# PUSH V-LAUFWERK
#######################################################################

- name: push-latest-fhtrier
  image: appleboy/drone-scp:1.6.2
  settings:
    host: ssh.hochschule-trier.de
    user:
      from_secret: ssh-user
    key:
      from_secret: ssh-key
    port: 22
    command_timeout: 2m
    target:
    - /dozenten/peschm/tgdb_ws1819
    source:
    - index.pdf
    - sql/schema_01.sql
    - sql/sqlplus-settings.sql
  when:
    repo:
    - fh-trier/tgdb_ws1819
    event:
    - push
    - cron

# PUSH GITHUB
#######################################################################

- name: push-latest-commit
  image: appleboy/drone-git-push:latest
  settings:
    branch: master
    remote: ssh://git@github.com/fh-trier/tgdb_ws1819.git
    force: true
    ssh_key:
      from_secret: ssh-key
  when:
    repo:
    - fh-trier/tgdb_ws1819
    event:
    - push
    - cron

# NOTIFY
###############################################################################

- name: notify
  image: drillster/drone-email
  environment:
    PLUGIN_HOST:
      from_secret: smtp_host
    PLUGIN_USERNAME:
      from_secret: smtp_username
    PLUGIN_PASSWORD:
      from_secret: smtp_password
    PLUGIN_FROM:
      from_secret: smtp_mail_address
  when:
    status:
    - changed
    - failure