-- Firmenvertreter
INSERT INTO CONTACTS (CONTACT_ID, CONTACT_FIRSTNAME, CONTACT_LASTNAME, CONTACT_PHONE, CONTACT_MOBILE, CONTACT_MAIL, SUPPLIER_ID)
VALUES (NEW_UUID(), 'Sabrina', 'Böckel', '+497854 22145 985', '+490554788112784', 'sabrina.boeckel@willems-gmbh.de', (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_NAME = 'Willems Metallhandel GmbH'));

-- Aktualisierung
UPDATE STORAGE
SET CONTACT_ID = (
  SELECT CONTACT_ID
  FROM CONTACTS
  WHERE CONTACT_MAIL = 'sabrina.boeckel@willems-gmbh.de'
)
WHERE CREATION_DATE < TO_DATE('2018-08-01', 'YYYY-MM-DD');