-- Titan Geschliffen 5000x4000x3
-- Gekauft von Michael Jakobs am 14 Juli 2018
-- Eingelagert in Lager X100
INSERT INTO STORAGE (STORAGE_ID, CONTACT_ID, EMPLOYEE_ID, METAL_ID, SHELF_ID, X_LENGTH, Y_LENGTH, METAL_THICKNESS, CREATION_DATE)
VALUES(
  NEW_UUID(),
  (SELECT CONTACT_ID FROM CONTACTS WHERE CONTACT_FIRSTNAME = 'Michael' AND CONTACT_LASTNAME = 'Jokobs'),
  (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_FIRSTNAME = 'Denis' AND EMPLOYEE_LASTNAME = 'Langkorn'),
  (SELECT METAL_ID FROM METALS WHERE METAL_NAME = 'Titan' AND METAL_PROPERTY IS NULL AND METAL_TYPE = 'Geschliffen'),
  (SELECT SHELF_ID FROM SHELFS WHERE SHELF_NAME = 'X' AND SHELF_NUMBER = 100),
  5000,
  4000,
  3,
  TO_DATE('2018-07-14', 'YYYY-MM-DD')
);

-- Titan Träne 2500x1000x1mm
-- Gekauft von Michael Jakobs am 17 August 2018
-- Eingelagert in Lager X50
INSERT INTO STORAGE (STORAGE_ID, CONTACT_ID, EMPLOYEE_ID, METAL_ID, SHELF_ID, X_LENGTH, Y_LENGTH, METAL_THICKNESS, CREATION_DATE)
VALUES(
  NEW_UUID(),
  (SELECT CONTACT_ID FROM CONTACTS WHERE CONTACT_FIRSTNAME = 'Michael' AND CONTACT_LASTNAME = 'Jokobs'),
  (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE EMPLOYEE_FIRSTNAME = 'Denis' AND EMPLOYEE_LASTNAME = 'Langkorn'),
  (SELECT METAL_ID FROM METALS WHERE METAL_NAME = 'Titan' AND METAL_PROPERTY IS NULL AND METAL_TYPE = 'Träne'),
  (SELECT SHELF_ID FROM SHELFS WHERE SHELF_NAME = 'X' AND SHELF_NUMBER = 50),
  2500,
  1000,
  1,
  TO_DATE('2018-08-17', 'YYYY-MM-DD')
);