-- Lieferant
INSERT INTO SUPPLIERS (SUPPLIER_ID, SUPPLIER_NAME, SUPPLIER_STREET, CITY_ID) VALUES (NEW_UUID(), 'Willems Metallhandel GmbH', 'Nord-Süd-Straße 17', (SELECT CITY_ID FROM CITIES WHERE CITY_POSTALCODE = 66740));

-- Firmenvertreter
INSERT INTO CONTACTS (CONTACT_ID, CONTACT_FIRSTNAME, CONTACT_LASTNAME, CONTACT_PHONE, CONTACT_MOBILE, CONTACT_MAIL, SUPPLIER_ID)
VALUES (NEW_UUID(), 'Michael', 'Jakobs', NULL, NULL, NULL, (SELECT SUPPLIER_ID FROM SUPPLIERS WHERE SUPPLIER_NAME = 'Willems Metallhandel GmbH'));