DELETE FROM STORAGE
WHERE EMPLOYEE_ID = (
  SELECT EMPLOYEE_ID
  FROM EMPLOYEES
  WHERE EMPLOYEE_FIRSTNAME = 'Lena'
  AND EMPLOYEE_LASTNAME = 'Hörnchen'
)
AND METAL_ID = (
  SELECT METAL_ID
  FROM METALS
  WHERE METAL_NAME = 'Aluminium'
  AND METAL_PROPERTY IS NULL
  AND METAL_TYPE = 'Geschliffen'
)
AND SHELF_ID = (
  SELECT SHELF_ID
  FROM SHELFS
  WHERE SHELF_NAME = 'A'
  AND SHELF_NUMBER = 80
);