-- Single-Row
INSERT INTO METALS (METAL_ID, METAL_NAME, METAL_PROPERTY, METAL_TYPE) VALUES(NEW_UUID(), 'Titan', NULL, 'Träne');
INSERT INTO METALS (METAL_ID, METAL_NAME, METAL_PROPERTY, METAL_TYPE) VALUES(NEW_UUID(), 'Titan', NULL, 'Geschliffen');
INSERT INTO METALS (METAL_ID, METAL_NAME, METAL_PROPERTY, METAL_TYPE) VALUES(NEW_UUID(), 'Gold', NULL, NULL);

-- Multi-Row
-- Achtung: Metall-Namen weichen ab!
INSERT ALL
  INTO METALS (METAL_ID, METAL_NAME, METAL_PROPERTY, METAL_TYPE) VALUES(NEW_UUID(), 'Chrome', NULL, NULL)
  INTO METALS (METAL_ID, METAL_NAME, METAL_PROPERTY, METAL_TYPE) VALUES(NEW_UUID(), 'Bronze', NULL, NULL)
  INTO METALS (METAL_ID, METAL_NAME, METAL_PROPERTY, METAL_TYPE) VALUES(NEW_UUID(), 'Silber', NULL, NULL)
  INTO METALS (METAL_ID, METAL_NAME, METAL_PROPERTY, METAL_TYPE) VALUES(NEW_UUID(), 'Nickel', NULL, NULL)
SELECT 1 FROM dual;
