-- Single-Row
INSERT INTO EMPLOYEES (
  EMPLOYEE_ID,
  EMPLOYEE_FIRSTNAME,
  EMPLOYEE_LASTNAME,
  EMPLOYEE_BIRTHDAY,
  EMPLOYEE_HIREDATE,
  EMPLOYEE_STREET,
  CITY_ID
)
VALUES (
  NEW_UUID(),
  'Dagobert',
  'Duck',
  TO_DATE('1986-08-22', 'YYYY-MM-DD'),
  TO_DATE('2006-12-02', 'YYYY-MM-DD'),
  'Brückenstraße 4',
  (SELECT CITY_ID FROM CITIES WHERE CITY_POSTALCODE = '50739')
);

-- Multi-Row
INSERT ALL
  INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_FIRSTNAME, EMPLOYEE_LASTNAME, EMPLOYEE_BIRTHDAY, EMPLOYEE_HIREDATE, EMPLOYEE_STREET, CITY_ID) VALUES (NEW_UUID(), 'Denis', 'Langkorn', TO_DATE('1986-08-22', 'YYYY-MM-DD'), TO_DATE('2006-12-02', 'YYYY-MM-DD'), 'Brückenstraße 4', (SELECT CITY_ID FROM CITIES WHERE CITY_POSTALCODE = '50739'))
  INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_FIRSTNAME, EMPLOYEE_LASTNAME, EMPLOYEE_BIRTHDAY, EMPLOYEE_HIREDATE, EMPLOYEE_STREET, CITY_ID) VALUES (NEW_UUID(), 'Mark', 'Heiliger', TO_DATE('1994-07-24', 'YYYY-MM-DD'), TO_DATE('2010-01-28', 'YYYY-MM-DD'), 'Zur Gabelstraße 5', (SELECT CITY_ID FROM CITIES WHERE CITY_POSTALCODE = '54292'))
  INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_FIRSTNAME, EMPLOYEE_LASTNAME, EMPLOYEE_BIRTHDAY, EMPLOYEE_HIREDATE, EMPLOYEE_STREET, CITY_ID) VALUES (NEW_UUID(), 'Charlotte', 'Maischberger', TO_DATE('1995-08-15', 'YYYY-MM-DD'), TO_DATE('2014-09-18', 'YYYY-MM-DD'), 'Zur Kapelle 12', (SELECT CITY_ID FROM CITIES WHERE CITY_POSTALCODE = '54290'))
SELECT 1 FROM dual;
