-- Single-Row
INSERT INTO METALS (METAL_ID, METAL_NAME, METAL_PROPERTY, METAL_TYPE, METAL_PRICE) VALUES(NEW_UUID(), 'Blei', NULL, NULL, 412.33);
INSERT INTO METALS (METAL_ID, METAL_NAME, METAL_PROPERTY, METAL_TYPE, METAL_PRICE) VALUES(NEW_UUID(), 'Titan', NULL, 'Träne', 1784.45);
INSERT INTO METALS (METAL_ID, METAL_NAME, METAL_PROPERTY, METAL_TYPE, METAL_PRICE) VALUES(NEW_UUID(), 'Titan', NULL, 'Geschliffen', 1655.12);
INSERT INTO METALS (METAL_ID, METAL_NAME, METAL_PROPERTY, METAL_TYPE, METAL_PRICE) VALUES(NEW_UUID(), 'Gold', NULL, NULL, 2101.44);

-- Multi-Row
-- Achtung: Metall-Namen weichen ab!
INSERT ALL
  INTO METALS (METAL_ID, METAL_NAME, METAL_PROPERTY, METAL_TYPE, METAL_PRICE) VALUES(NEW_UUID(), 'Chrome', NULL, NULL, 745.33)
  INTO METALS (METAL_ID, METAL_NAME, METAL_PROPERTY, METAL_TYPE, METAL_PRICE) VALUES(NEW_UUID(), 'Bronze', NULL, NULL, 1784.45)
  INTO METALS (METAL_ID, METAL_NAME, METAL_PROPERTY, METAL_TYPE, METAL_PRICE) VALUES(NEW_UUID(), 'Silber', NULL, NULL, 1655.12)
  INTO METALS (METAL_ID, METAL_NAME, METAL_PROPERTY, METAL_TYPE, METAL_PRICE) VALUES(NEW_UUID(), 'Nickel', NULL, NULL, 2101.44)
SELECT 1 FROM dual;
