-- Single-Row
INSERT INTO SHELFS (SHELF_ID, SHELF_NAME, SHELF_NUMBER) VALUES(NEW_UUID(), 'X', 50);
INSERT INTO SHELFS (SHELF_ID, SHELF_NAME, SHELF_NUMBER) VALUES(NEW_UUID(), 'X', 100);

-- Multi-Row
-- Achtung: Regal-Nummern weichen ab!
INSERT ALL
  INTO SHELFS (SHELF_ID, SHELF_NAME, SHELF_NUMBER) VALUES(NEW_UUID(), 'X', 25)
  INTO SHELFS (SHELF_ID, SHELF_NAME, SHELF_NUMBER) VALUES(NEW_UUID(), 'X', 75)
SELECT 1 FROM dual;
