-- Aufgabe 4.4
ALTER TABLE METALS
ADD PRICE NUMBER(9,2);


UPDATE METALS
SET PRICE = 877.45
WHERE METAL_NAME = 'Edelstahl'
AND METAL_PROPERTY = '1.4301'
AND METAL_TYPE IS NULL;

UPDATE METALS
SET PRICE = 1248.14
WHERE METAL_NAME = 'Edelstahl'
AND METAL_PROPERTY = '1.4301'
AND METAL_TYPE = 'Träne';

UPDATE METALS
SET PRICE = 912.78
WHERE METAL_NAME = 'Edelstahl'
AND METAL_PROPERTY = '1.4301'
AND METAL_TYPE = 'Geschliffen';


UPDATE METALS
SET PRICE = 1017.55
WHERE METAL_NAME = 'Edelstahl'
AND METAL_PROPERTY = '1.6582'
AND METAL_TYPE IS NULL;

UPDATE METALS
SET PRICE = 1351.45
WHERE METAL_NAME = 'Edelstahl'
AND METAL_PROPERTY = '1.6582'
AND METAL_TYPE = 'Träne';

UPDATE METALS
SET PRICE = 1115.18
WHERE METAL_NAME = 'Edelstahl'
AND METAL_PROPERTY = '1.6582'
AND METAL_TYPE = 'Geschliffen';


UPDATE METALS
SET PRICE = 899.05
WHERE METAL_NAME = 'Edelstahl'
AND METAL_PROPERTY = '1.4452'
AND METAL_TYPE IS NULL;

UPDATE METALS
SET PRICE = 1057.49
WHERE METAL_NAME = 'Edelstahl'
AND METAL_PROPERTY = '1.4452'
AND METAL_TYPE = 'Träne';

UPDATE METALS
SET PRICE = 974.62
WHERE METAL_NAME = 'Edelstahl'
AND METAL_PROPERTY = '1.4452'
AND METAL_TYPE = 'Geschliffen';


UPDATE METALS
SET PRICE = 541.86
WHERE METAL_NAME = 'Schwarzstahl'
AND METAL_PROPERTY = 'S235'
AND METAL_TYPE IS NULL;

UPDATE METALS
SET PRICE = 561.78
WHERE METAL_NAME = 'Schwarzstahl'
AND METAL_PROPERTY = 'S355'
AND METAL_TYPE IS NULL;


UPDATE METALS
SET PRICE = 215.77
WHERE METAL_NAME = 'Kupfer'
AND METAL_PROPERTY IS NULL
AND METAL_TYPE IS NULL;


UPDATE METALS
SET PRICE = 187.55
WHERE METAL_NAME = 'Messing'
AND METAL_PROPERTY IS NULL
AND METAL_TYPE IS NULL;


UPDATE METALS
SET PRICE = 125.77
WHERE METAL_NAME = 'Aluminium'
AND METAL_PROPERTY IS NULL
AND METAL_TYPE = 'Geschliffen';

UPDATE METALS
SET PRICE = 147.87
WHERE METAL_NAME = 'Aluminium'
AND METAL_PROPERTY IS NULL
AND METAL_TYPE = 'Träne';

UPDATE METALS
SET PRICE = 110.12
WHERE METAL_NAME = 'Aluminium'
AND METAL_PROPERTY IS NULL
AND METAL_TYPE IS NULL;
