SET LINESIZE 200
SET LONG 327679
SET NUMWIDTH 9
SET NULL (NULL)
SET PAGESIZE 50
SET SERVEROUTPUT ON
SET SQLPROMPT "_USER'@'_CONNECT_IDENTIFIER> "
SET UNDERLINE =

COLUMN CITY_ID FORMAT a37
COLUMN CITY_NAME FORMAT a15
COLUMN CITY_POSTALCODE FORMAT a15

COLUMN CONTACT_ID FORMAT a37
COLUMN CONTACT_FIRSTNAME FORMAT a17
COLUMN CONTACT_LASTNAME FORMAT a16
COLUMN CONTACT_PHONE FORMAT a18
COLUMN CONTACT_MOBILE FORMAT a18
COLUMN CONTACT_MAIL FORMAT a32

COLUMN COUNTRY_ID FORMAT a37
COLUMN COUNTRY_NAME FORMAT a32

COLUMN EMPLOYEE_ID FORMAT a37
COLUMN EMPLOYEE_FIRSTNAME FORMAT a18
COLUMN EMPLOYEE_LASTNAME FORMAT a17
COLUMN EMPLOYEE_STREET FORMAT a20

COLUMN METAL_ID FORMAT a37
COLUMN METAL_NAME FORMAT a16
COLUMN METAL_PROPERTY FORMAT a16
COLUMN METAL_TYPE FORMAT a12

COLUMN SHELF_ID FORMAT a37
COLUMN SHELF_NAME FORMAT a10
COLUMN SHELF_NUMBER FORMAT 999

COLUMN STATE_ID FORMAT a37
COLUMN STATE_NAME FORMAT a32

COLUMN STORAGE_ID FORMAT a37

COLUMN SUPPLIER_ID FORMAT a37
COLUMN SUPPLIER_NAME FORMAT a32
COLUMN SUPPLIER_STREET FORMAT a32
